### ISSUE TITLE
Error Unpickling the Cora.npz data (and others)

### ISSUE THREAD

**Issue by xDangerousDinox** [snap-research/graphless-neural-networks#8]
Hi! I am trying to start running the code but I have encountered the following error I can't figure out when trying to load the .npz cora file.
Using backend: pytorch
WARNING:root:The OGB package is out of date. Your version is 1.3.3, while the latest version is 1.3.5.
Traceback (most recent call last):
  File "/home/aaron/anaconda3/envs/glnn/lib/python3.6/site-packages/numpy/lib/npyio.py", line 460, in load
    return pickle.load(fid, **pickle_kwargs)
_pickle.UnpicklingError: invalid load key, '\x0a'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_teacher.py", line 346, in <module>
    main()
  File "train_teacher.py", line 329, in main
    score = run(args)
  File "train_teacher.py", line 210, in run
    labelrate_val=args.labelrate_val,
  File "/home/aaron/graphless-neural-networks/dataloader.py", line 49, in load_data
    kwargs["labelrate_val"],
  File "/home/aaron/graphless-neural-networks/dataloader.py", line 85, in load_cpf_data
    data = load_npz_to_sparse_graph(data_path)
  File "/home/aaron/graphless-neural-networks/dataloader.py", line 526, in load_npz_to_sparse_graph
    with np.load(file_name, allow_pickle=True) as loader:
  File "/home/aaron/anaconda3/envs/glnn/lib/python3.6/site-packages/numpy/lib/npyio.py", line 463, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file PosixPath('/home/aaron/graphless-neural-networks/data/cora.npz') as a pickle

I think it has something to do with how the file is saved with different versions of numpy? I have used the same exact requirements.txt file for the conda environment.

Thanks!

**Comment by xDangerousDinox** [comment]
Fixed! I apologize for jumping the gun. I downloaded the .npz files using the wget command and this for some reason downloaded it as a different file type that wasn't immediately obvious. If anyone else gets this error just double check what you actually have is a npz file.
